trigger:
- dev

pool: jesusagentpool

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.9.1'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'any cpu'
    configuration: 'release'
    msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: terraform
    Contents: |
     **/*.tf
     **/*.tfvars
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: ARMvmDeployment
    Contents: '**/*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory) copy'
  inputs:
    SourceFolder: AzureWebApp
    Contents: '**/*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\$(BuildConfiguration)\*test*.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    

